// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcd2BBArf3xAkm-muS9qY6TGJ9cnu82QQ',
    appId: '1:16924622546:web:48cfe388dd2a27e6cff70b',
    messagingSenderId: '16924622546',
    projectId: 'dr-fb-12082024',
    authDomain: 'dr-fb-12082024.firebaseapp.com',
    storageBucket: 'dr-fb-12082024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJoztSXu8s8VVzLrOygz674ILOBDTZGqI',
    appId: '1:16924622546:android:1d0997d97568db1fcff70b',
    messagingSenderId: '16924622546',
    projectId: 'dr-fb-12082024',
    storageBucket: 'dr-fb-12082024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSuRfGk_4WWanRwP_vsWkXLVT5pWthyjw',
    appId: '1:16924622546:ios:3be20989e42181c7cff70b',
    messagingSenderId: '16924622546',
    projectId: 'dr-fb-12082024',
    storageBucket: 'dr-fb-12082024.appspot.com',
    iosBundleId: 'com.example.drfb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSuRfGk_4WWanRwP_vsWkXLVT5pWthyjw',
    appId: '1:16924622546:ios:3be20989e42181c7cff70b',
    messagingSenderId: '16924622546',
    projectId: 'dr-fb-12082024',
    storageBucket: 'dr-fb-12082024.appspot.com',
    iosBundleId: 'com.example.drfb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcd2BBArf3xAkm-muS9qY6TGJ9cnu82QQ',
    appId: '1:16924622546:web:4fb24cb2028e1dfbcff70b',
    messagingSenderId: '16924622546',
    projectId: 'dr-fb-12082024',
    authDomain: 'dr-fb-12082024.firebaseapp.com',
    storageBucket: 'dr-fb-12082024.appspot.com',
  );
}
