// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnPaM3TXtg1IPqvNbxMUNc0NhpLa36Suk',
    appId: '1:723284804784:web:c559c06d798811784f6775',
    messagingSenderId: '723284804784',
    projectId: 'drfn-d6eb6',
    authDomain: 'drfn-d6eb6.firebaseapp.com',
    databaseURL: 'https://drfn-d6eb6-default-rtdb.firebaseio.com',
    storageBucket: 'drfn-d6eb6.appspot.com',
    measurementId: 'G-4PTMBBV5CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArKLRzej6V7MFq05uF6BbB3_JaW0RIbeE',
    appId: '1:723284804784:android:08670a313476eeb44f6775',
    messagingSenderId: '723284804784',
    projectId: 'drfn-d6eb6',
    databaseURL: 'https://drfn-d6eb6-default-rtdb.firebaseio.com',
    storageBucket: 'drfn-d6eb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3rFUOj0mciz9_m-0Ow0IAIklavltYGns',
    appId: '1:723284804784:ios:950b89aeb612cdca4f6775',
    messagingSenderId: '723284804784',
    projectId: 'drfn-d6eb6',
    databaseURL: 'https://drfn-d6eb6-default-rtdb.firebaseio.com',
    storageBucket: 'drfn-d6eb6.appspot.com',
    iosBundleId: 'com.example.input',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3rFUOj0mciz9_m-0Ow0IAIklavltYGns',
    appId: '1:723284804784:ios:950b89aeb612cdca4f6775',
    messagingSenderId: '723284804784',
    projectId: 'drfn-d6eb6',
    databaseURL: 'https://drfn-d6eb6-default-rtdb.firebaseio.com',
    storageBucket: 'drfn-d6eb6.appspot.com',
    iosBundleId: 'com.example.input',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnPaM3TXtg1IPqvNbxMUNc0NhpLa36Suk',
    appId: '1:723284804784:web:4f07d6c35c2100d14f6775',
    messagingSenderId: '723284804784',
    projectId: 'drfn-d6eb6',
    authDomain: 'drfn-d6eb6.firebaseapp.com',
    databaseURL: 'https://drfn-d6eb6-default-rtdb.firebaseio.com',
    storageBucket: 'drfn-d6eb6.appspot.com',
    measurementId: 'G-FL5JWNVKHT',
  );
}
